#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_LGSIC_SW49107)	+= touch_sw49107.o
obj-$(CONFIG_LGE_TOUCH_LGSIC_SW49107)	+= touch_sw49107_prd.o
