#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.

# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8607)	+= FT8607/
obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8607)	+= FT8607/
obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8607)	+= fts/

obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8006M)	+= FT8006M/
obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8006M)	+= FT8006M/
obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8006M)	+= fts/
