#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8006M)         += touch_ft8006m.o
obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8006M)         += touch_ft8006m_prd.o