#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_LGSIC_SW49106)	+= touch_sw49106.o
obj-$(CONFIG_LGE_TOUCH_LGSIC_SW49106)	+= touch_sw49106_abt.o
obj-$(CONFIG_LGE_TOUCH_LGSIC_SW49106)	+= touch_sw49106_prd.o