ifeq ($(CONFIG_MACH_MSM8940_SF3_SPR_US),y)
DTS_TARGET := msm8940-sf3_spr_us
endif

ifeq ($(CONFIG_MACH_MSM8940_SF3_TMO_US),y)
DTS_TARGET := msm8940-sf3_tmo_us
endif

ifeq ($(CONFIG_MACH_MSM8940_TF8_TMO_US),y)
DTS_TARGET := msm8940-tf8_tmo_us
endif

ifeq ($(CONFIG_MACH_MSM8940_TF8_GLOBAL_CA),y)
DTS_TARGET := msm8940-tf8_global_ca
endif

ifeq ($(CONFIG_MACH_MSM8940_TF8_LGU_KR),y)
DTS_TARGET := msm8940-tf8_lgu_kr
endif

ifeq ($(CONFIG_MACH_MSM8940_SF3_GLOBAL_CA),y)
DTS_TARGET := msm8940-sf3_global_ca
endif

ifeq ($(CONFIG_MACH_MSM8940_SF3_MPCS_US),y)
DTS_TARGET := msm8940-sf3_mpcs_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV3_MPCS_US),y)
DTS_TARGET := msm8917-lv3_mpcs_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV3_TMO_US),y)
DTS_TARGET := msm8917-lv3_tmo_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV3_USC_US),y)
DTS_TARGET := msm8917-lv3_usc_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV3_LGU_KR),y)
DTS_TARGET := msm8917-lv3_lgu_kr
endif

ifeq ($(CONFIG_MACH_MSM8917_LV3_SKT_KR),y)
DTS_TARGET := msm8917-lv3_skt_kr
endif

ifeq ($(CONFIG_MACH_MSM8917_LV3_KT_KR),y)
DTS_TARGET := msm8917-lv3_kt_kr
endif

ifeq ($(CONFIG_MACH_MSM8917_LV3_GLOBAL_COM),y)
DTS_TARGET := msm8917-lv3_global_com
endif

ifeq ($(CONFIG_MACH_MSM8917_LV7_TRF_US),y)
DTS_TARGET := msm8917-lv7_trf_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV7_TRF_US_VZW),y)
DTS_TARGET := msm8917-lv7_trf_us_vzw
endif

ifeq ($(CONFIG_MACH_MSM8917_LV7_CCT_US_VZW),y)
DTS_TARGET := msm8917-lv7_cct_us_vzw
endif

ifeq ($(CONFIG_MACH_MSM8917_LV7_CRK_US),y)
DTS_TARGET := msm8917-lv7_crk_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV7_GLOBAL_CA),y)
DTS_TARGET := msm8917-lv7_global_ca
endif

ifeq ($(CONFIG_MACH_MSM8917_LV7V_LAO_COM),y)
DTS_TARGET := msm8917-lv7v_lao_com
endif

ifeq ($(CONFIG_MACH_MSM8917_LV7_LAO_COM),y)
DTS_TARGET := msm8917-lv7_lao_com
endif

ifeq ($(CONFIG_MACH_MSM8917_B6_JCM_JP),y)
DTS_TARGET := msm8917-b6_jcm_jp
endif

ifeq ($(CONFIG_MACH_MSM8917_B6_LGU_KR),y)
DTS_TARGET := msm8917-b6_lgu_kr
endif

ifeq ($(CONFIG_MACH_MSM8917_LV517N_ATT_US),y)
DTS_TARGET := msm8917-lv517n_att_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV517_CRK_US),y)
DTS_TARGET := msm8917-lv517_crk_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV517_CLR_PR),y)
DTS_TARGET := msm8917-lv517_crk_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV517_TMO_US),y)
DTS_TARGET := msm8917-lv517_tmo_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV517_MPCS_US),y)
DTS_TARGET := msm8917-lv517_mpcs_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV517_TRF_US),y)
DTS_TARGET := msm8917-lv517_trf_us
endif

ifeq ($(CONFIG_MACH_MSM8917_LV517_VZW),y)
DTS_TARGET := msm8917-lv517_vzw
endif

ifeq ($(CONFIG_MACH_MSM8917_SF317_TRF_US),y)
DTS_TARGET := msm8917-sf317_trf_us
endif

ifeq ($(CONFIG_MACH_MSM8917_SF317_TRF_US_VZW),y)
DTS_TARGET := msm8917-sf317_trf_us_vzw
endif

ifeq ($(CONFIG_MACH_MSM8917_SF317_CRK_US),y)
DTS_TARGET := msm8917-sf317_crk_us
endif

ifeq ($(CONFIG_MACH_MSM8940_LV9_ATT_US),y)
DTS_TARGET := msm8940-lv9_att_us
endif

ifeq ($(CONFIG_MACH_MSM8940_LV9_NAO_US),y)
DTS_TARGET := msm8940-lv9_nao_us
endif

ifeq ($(CONFIG_MACH_MSM8940_LV9_GLOBAL_COM),y)
DTS_TARGET := msm8940-lv9_global_com
endif

ifeq ($(CONFIG_MACH_MSM8940_MH_GLOBAL_COM),y)
DTS_TARGET := msm8940-mh_global_com
endif

ifeq ($(CONFIG_MACH_MSM8940_MH_GLOBAL_LDU),y)
DTS_TARGET := msm8940-mh_global_ldu
endif

ifeq ($(CONFIG_MACH_MSM8940_MH_TMO_US),y)
DTS_TARGET := msm8940-mh_tmo_us
endif

ifeq ($(CONFIG_MACH_MSM8940_MH_CRK_US),y)
DTS_TARGET := msm8940-mh_crk_us
endif

ifeq ($(CONFIG_MACH_MSM8940_MH_MPCS_US),y)
DTS_TARGET := msm8940-mh_mpcs_us
endif

ifeq ($(CONFIG_MACH_MSM8940_MH_TRF_US),y)
DTS_TARGET := msm8940-mh_trf_us
endif

ifeq ($(CONFIG_MACH_MSM8940_MH_LGU_KR),y)
DTS_TARGET := msm8940-mh_lgu_kr
endif

ifeq ($(CONFIG_MACH_MSM8940_MH_SKT_KR),y)
DTS_TARGET := msm8940-mh_skt_kr
endif

ifeq ($(CONFIG_MACH_MSM8940_MH_KT_KR),y)
DTS_TARGET := msm8940-mh_kt_kr
endif

ifeq ($(CONFIG_MACH_MSM8940_MH_GLOBAL_CA),y)
DTS_TARGET := msm8940-mh_global_ca
endif

ifeq ($(CONFIG_MACH_MSM8940_MH_LAO_COM),y)
DTS_TARGET := msm8940-mh_lao_com
endif

ifeq ($(CONFIG_MACH_MSM8917_CV1_LAO_COM),y)
DTS_TARGET := msm8917-cv1_lao_com
endif

ifeq ($(CONFIG_MACH_MSM8917_CV3_LGU_KR),y)
DTS_TARGET := msm8917-cv3_lgu_kr
endif

ifeq ($(CONFIG_MACH_MSM8917_CV3_SKT_KR),y)
DTS_TARGET := msm8917-cv3_skt_kr
endif

ifeq ($(CONFIG_MACH_MSM8917_CV3_KT_KR),y)
DTS_TARGET := msm8917-cv3_kt_kr
endif

ifeq ($(CONFIG_MACH_MSM8917_CV3_LAO_COM),y)
DTS_TARGET := msm8917-cv3_lao_com
endif

ifeq ($(CONFIG_MACH_SDM450_CV7A_LGU_LDU),y)
DTS_TARGET := sdm450-cv7a_lgu_ldu
endif


ifeq ($(CONFIG_MACH_SDM450_CV7A_LAO_COM),y)
DTS_TARGET := sdm450-cv7a_lao_com
endif

ifeq ($(CONFIG_MACH_SDM450_CV7A_LAO_COM_NONAB),y)
DTS_TARGET := sdm450-cv7a_lao_com_nonAB
endif


ifeq ($(CONFIG_MACH_SDM450_CV7A_KR),y)
DTS_TARGET := sdm450-cv7a_kr
endif

ifeq ($(CONFIG_MACH_SDM450_CV5A_LAO_COM),y)
DTS_TARGET := sdm450-cv5a_lao_com
endif

ifeq ($(CONFIG_MACH_SDM450_CV5A_DCM_JP),y)
DTS_TARGET := sdm450-cv5a_dcm_jp
endif

ifeq ($(CONFIG_MACH_SDM450_CV5A_TMO_US_SPROUT),y)
DTS_TARGET := sdm450-cv5a_tmo_us_sprout
endif

ifeq ($(CONFIG_MACH_SDM450_CV5A_LGU_KR),y)
DTS_TARGET := sdm450-cv5a_lgu_kr
endif

ifeq ($(CONFIG_MACH_SDM450_CV5A_KT_KR),y)
DTS_TARGET := sdm450-cv5a_kt_kr
endif

ifeq ($(CONFIG_MACH_SDM450_CV5A_SKT_KR),y)
DTS_TARGET := sdm450-cv5a_skt_kr
endif

ifeq ($(CONFIG_MACH_SDM450_CV5A_LGU_LDU),y)
DTS_TARGET := sdm450-cv5a_lgu_ldu
endif

ALL_DTS := $(notdir $(wildcard echo $(srctree)/$(src)/$(DTS_TARGET)/*.dts))
dtb-y += $(patsubst %.dts,%.dtb,$(ALL_DTS))

DTB_NAMES := $(subst $\",,$(CONFIG_BUILD_ARM_APPENDED_DTB_IMAGE_NAMES))
ifneq ($(DTB_NAMES),)
DTB_LIST := $(addsuffix .dtb,$(DTB_NAMES))
else
DTB_LIST := $(dtb-y)
endif

ifeq ($(CONFIG_ARM64),y)
always  := $(addprefix ../,$(DTB_LIST))

$(obj)/../%.dtb: $(src)/$(DTS_TARGET)/%.dts FORCE
	$(call if_changed_dep,dtc)
else
targets += dtbs
targets += $(addprefix ../, $(DTB_LIST))

$(obj)/../%.dtb: $(src)/$(DTS_TARGET)/%.dts FORCE
        $(call if_changed_dep,dtc)

dtbs: $(addprefix $(obj)/$(DTS_TARGET)/,$(DTB_LIST))
endif

clean-files := *.dtb
