#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_LG4894)	+= touch_lg4894.o
obj-$(CONFIG_LGE_TOUCH_LG4894)	+= touch_lg4894_abt.o
obj-$(CONFIG_LGE_TOUCH_LG4894)	+= touch_lg4894_prd.o